### ISSUE TITLE
Bug: rest:dial calls remain in sessionTracker.sessions

### ISSUE THREAD

**Issue by Catharsis68** [jambonz/jambonz-feature-server#401] opened 2023-07-20 12:20 UTC
We are facing the issue that our feature-server pods remain in "terminating" state.

After some investigation we realized, that the calls done via api-server `v1/Accounts/:accountSid/Calls` directly to FS remain in `sessionTracker.sessions`

```
// app.js
function handle(signal) {
  ...,
  if (getCount() === 0) {   // <= this will never be fulfilled
    logger.info('no calls in progress, exiting'); 
    process.exit(0);
  }
}
```

**Comment by xquanluu** [comment] 2023-07-20 13:49
Hi @Catharsis68 

I cannot reproduce the issue. Could you please give me some hint on how to reproduce it.

I'm testing with this create call version 1:

```
{
    "application_sid": "d2bb9346-362c-4fd7-bf45-ca30755e684d",
    "from": "15083728299",
    "to": {
        "type": "user",
        "name": "xhoaluu@hoan.jambonz.one"
    }
}
```

The jambonz application  json is just a say verb.

```[
{
  "verb": "say",
  "text": "hi there! How are you, I'm fine thank you and you, may i help you for today, can I have more usecase than now"
}
]
```

```30|jambonz-feature-server  | {"level":30,"time":1689860581606,"pid":2322116,"hostname":"ip-10-0-214-82","msg":"SessionTracker:add callSid 87d808dd-99c3-46cf-b974-72db19af7d68, we have 1 session being tracked"}

30|jambonz-feature-server  | {"level":20,"time":1689860594588,"pid":2322116,"hostname":"ip-10-0-214-82","callSid":"87d808dd-99c3-46cf-b974-72db19af7d68","callId":"2fbc704a-a1a6-123c-59b7-161343ac42f3","accountSid":"9351f46a-678c-43f5-b8a6-d4eb58d131af","traceId":"3b33986f4afc44dbbdf6db98c211386a","msg":"CallSession: call terminated by jambonz"}
30|jambonz-feature-server  | {"level":30,"time":1689860594592,"pid":2322116,"hostname":"ip-10-0-214-82","msg":"SessionTracker:remove callSid 87d808dd-99c3-46cf-b974-72db19af7d68, we have 0 being tracked"}```

**Comment by Catharsis68** [comment] 2023-07-20 15:51
Hey :)

```json
{
"application_sid": "d6a219b6-683a-4e04-835a-dabd092edf13",
    "from": "441772503124", 
    "to": {
        "type": "phone",
        "number": "my-mobile"
    }    
}
```

Create an Application and point to this wss: wss://frindt.ap.ngrok.io/79cdf289270cb8b1403b945b712b299c03ebea79a2dbe67f7d282620a86383fd/voiceGateway

At the moment my ngrok is off, that results also in the remaining session.

Normally our application is connected to one voice bot and the "to" number is another voice bot. So a ping pong health check for voice.

After receiving a SIGTERM we added an interval that prints every x seconds the remaining callSids
![Screenshot from 2023-07-20 17-42-25](https://github.com/jambonz/jambonz-feature-server/assets/6165055/7f4da624-184e-4238-9f91-f7320954e242)

**Comment by xquanluu** [comment] 2023-07-20 23:13
Hi 

I'm using jambonz v0.8.4, I have created and point calling webhook to you wss server.

I called restAPI and call received at my client, but cannot hear anything due to the socket server is not opened. I droped the call. and still see call is cleared in tracker

```
30|jambonz-feature-server  | {"level":30,"time":1689894646785,"pid":2322116,"hostname":"ip-10-0-214-82","msg":"SessionTracker:remove callSid fed7031a-e50f-4a67-8037-a4553e0c06b3, we have 0 being tracked"}
```

**Comment by davehorton** [comment] 2023-08-02 16:52
fixed in https://github.com/jambonz/jambonz-feature-server/commit/48b182c8911adbed67f26b8997cacbc50cd27338

**Closed by davehorton** 2023-08-02 16:52 UTC
