### ISSUE TITLE
Relative path on listen ws endpoint

### ISSUE THREAD

**Issue by ajukes** [jambonz/jambonz-feature-server#3] opened 2020-02-03 21:14 UTC
When Listen verb has relative url. for example /record. Jambones throws the following error.

```
2|jambonz-feature-server  | TypeError: Cannot read property 'originalRequest' of undefined
2|jambonz-feature-server  |     at TaskListen.normalizeUrl (/home/deploy/jambonz-feature-server/lib/tasks/task.js:64:35)
2|jambonz-feature-server  |     at new TaskListen (/home/deploy/jambonz-feature-server/lib/tasks/listen.js:19:22)
2|jambonz-feature-server  |     at makeTask (/home/deploy/jambonz-feature-server/lib/tasks/make_task.js:41:14)
2|jambonz-feature-server  |     at new TaskDial (/home/deploy/jambonz-feature-server/lib/tasks/dial.js:59:25)
2|jambonz-feature-server  |     at makeTask (/home/deploy/jambonz-feature-server/lib/tasks/make_task.js:23:14)
2|jambonz-feature-server  |     at normalizeJamones.map (/home/deploy/jambonz-feature-server/lib/utils/retrieve-app.js:28:56)
2|jambonz-feature-server  |     at Array.map (<anonymous>)
2|jambonz-feature-server  |     at retrieveApp (/home/deploy/jambonz-feature-server/lib/utils/retrieve-app.js:28:41)
2|jambonz-feature-server  |     at Request.request [as _callback] (/home/deploy/jambonz-feature-server/lib/utils/notifiers.js:35:26)
2|jambonz-feature-server  |     at Request.self.callback (/home/deploy/jambonz-feature-server/node_modules/request/request.js:185:22)
```

I have tried secured and unsecured ws endpoints

**Comment by davehorton** [comment] 2020-02-04 16:36
duplicate of #6

**Closed by davehorton** 2020-02-04 16:36 UTC
Labels: duplicate
