### ISSUE TITLE
voice mail hints for en-US is too long that freeswitch transcribe module cannot make connection

### ISSUE THREAD

**Issue by xquanluu** [jambonz/jambonz-feature-server#871] opened 2024-08-20 04:24 UTC
With long hints provided in example-voicemail-greetings.json for en-US, that freeswitch module cannot make connection to the vendor with that long hints

Deepgram:

```
20750,163     99%

2024-08-19 15:14:56.072561 94.57% [ERR] lws_glue.cpp:482 [2024/08/19 15:14:56:0798] E: Ran out of header data space
```

Google:

```
2024-08-19 15:44:30.652560 90.57% [ERR] google_glue_v1.cpp:236 grpc_read_thread: error Invalid recognition 'config': Context phrase with 106 characters found, but max is 100. (3)
```

**Comment by davehorton** [comment] 2024-08-20 11:06
This is a duplicate of https://github.com/jambonz/jambonz-feature-server/issues/870 which I asked Raj to work on

**Comment by davehorton** [comment] 2024-08-20 11:31
PR merged

**Closed by davehorton** 2024-08-20 11:31 UTC
